### PR TITLE
Improved multi-day events

### PR DESCRIPTION
**Pull request by mygrexit**
Added a feature to show how long multi-day events last. This makes the event titles more informative and easy to read while it also supports different languages.

Also I tried to improve event handling in calendar and added support for multi-day events.

I used arrow for both improvements in order to stick with the existing modules.

### CODE REVIEW

**Comment by mygrexit** [comment]
Added the commit for the multi-event support.

**Comment by mygrexit** [comment]
TODO: 

Days with multi day events should look different that days with single day events only. Days with "mixed" events should look different from both.

**Comment by aceisace** [comment]
Could you provide an image so it's easier to identify the actual changes on the display?

**Comment by mygrexit** [comment]
> Could you provide an image so it's easier to identify the actual changes on the display?

Sure!

As you can see, the duration (4 days) or (4 dias) in this case is behind the event and the multi day event is being handled like a _days_with_events_

Currently working on a graphical distinction between the border types.

**Review by aceisace — APPROVED** [review]
looks okay, approving

**Comment by aceisace** [comment]
merge attempt #1

**Pull request merged**
